SCREEN_WIDTH = 100
SCREEN_HEIGHT = 50

WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

AGENT_SIZE = 1
FPS = 120

MOVE_LEFT = 1
MOVE_TOP = 2
MOVE_RIGHT = 3
MOVE_DOWN = 4
MOVE_STOP = 4
MOVE_LEFT_UP = 5
MOVE_RIGHT_UP = 6
MOVE_RIGHT_DOWN = 7
MOVE_LEFT_DOWN = 8

MOVES = [MOVE_LEFT, MOVE_TOP, MOVE_RIGHT, MOVE_STOP,
         MOVE_LEFT_UP, MOVE_RIGHT_UP, MOVE_RIGHT_DOWN, MOVE_LEFT_DOWN]

SCAN_RADIUS = 5
SCAN_DIAMETER = SCAN_RADIUS * 2 + 1

# rabbit

RABBIT_COLOR = (131, 132, 133)
RABBIT_SPEED = 3
RABBIT_NUMBER = 1

# grass

GRASS_NUMBER = -1
GRASS_SPEED = 0
GRASS_COLOR = (161, 181, 74)

# food

FOOD_NUMBER = 3
FOOD_SPEED = 0
FOOD_COLOR = (38, 145, 117)

# fox

FOX_COLOR = (252, 186, 3)
FOX_NUMBER = 2
FOX_SPEED = 5


SAME_MOVES_PENALTY = 5
REFILL_WORLD_THRESHOLD = 1.35
REFILL_WORLD_EPOCH_THRESHOLD = 100
DECAY = 250
